language: elixir
elixir:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
otp_release:
  - 17.5
  - 18.3
  - 19.3
  - 20.3
  - 21.3
  - 22.0
env: MIX_ENV=test
sudo: false # faster builds
notifications:
  email: false
script:
  - mix compile
  - mix test
